CFLAGS+=-fPIC -Wall -g -std=gnu11 -I../include
LDFLAGS+=-shared

LIBDIR=../lib
LIBNAME=libLockFile.so
LIB=$(LIBDIR)/$(LIBNAME)

SOURCES=$(wildcard *.c)
OBJS=$(SOURCES:.c=.o)

$(LIB) $(LIBNAME): $(OBJS)
	$(CC) $(LDFLAGS) $^ -o $@

clean:
	- rm -f $(LIB) *.o

.PHONY: clean
